# permissions for end users to edit imagepolicyargocdupdates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepolicyargocdupdate-editor-role
rules:
- apiGroups:
  - apps.bigkevmcd.com
  resources:
  - imagepolicyargocdupdates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.bigkevmcd.com
  resources:
  - imagepolicyargocdupdates/status
  verbs:
  - get
