# permissions for end users to view imagepolicyargocdupdates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepolicyargocdupdate-viewer-role
rules:
- apiGroups:
  - apps.bigkevmcd.com
  resources:
  - imagepolicyargocdupdates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.bigkevmcd.com
  resources:
  - imagepolicyargocdupdates/status
  verbs:
  - get
