apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-demo-application
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: examples/kustomize/overlays/dev
    repoURL: https://github.com/bigkevmcd/go-demo.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
